### ISSUE TITLE
AccessViolationException when calling the callback function

### ISSUE THREAD

**Issue by EugenyCh** [BeanCheeseBurrito/Box2D.NET#1]
Instead of:
`public static extern void WorldRayCast(WorldId worldId, Vec2 origin, Vec2 translation, QueryFilter filter, System.IntPtr* fcn, void* context);`
You need to use:
`public static extern void WorldRayCast(WorldId worldId, Vec2 origin, Vec2 translation, QueryFilter filter, System.IntPtr fcn, void* context);`
The difference in `fcn`.
Otherwise, an error occurs:
_System.AccessViolationException: 'Attempted to read or write protected memory. This is often an indication that other memory is corrupt.'_

**Comment by BeanCheeseBurrito** [comment]
Thanks! I fixed the issue and function pointers should be generated correctly now. I updated the bindings to the latest box2c commit and pushed a new nuget package as well.

https://www.nuget.org/packages/Box2D.NET.Debug/0.0.8
